#!/bin/bash

WORKINGDIRECTORY=/neutron_ocata
export TEMPEST_CONFIG_DIR=$WORKINGDIRECTORY/etc

. init-functions

validate_os_creds

cd $WORKINGDIRECTORY
. ./bin/activate
./tools/populate-conf-from-env


